import { useEffect, useMemo, useState } from 'react'
import { Routes, Route, Link, NavLink, useLocation, useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { Search, MapPin, Navigation, RefreshCw, Wind, Droplets, Gauge, Eye, Sunrise, Sunset, ArrowUpRight, Plus, Heart, Menu, X, Sparkles, Umbrella, Compass, CloudSun } from 'lucide-react'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, AreaChart, Area } from 'recharts'
import { defaultLocation, fetchWeather, searchLocations, supportedCities } from './services/weatherApi'
import type { Location, WeatherData } from './types'
import { formatDate, formatDay, formatHour, weatherIcon, weatherLabel } from './utils/weather'

function App() {
  const [location, setLocation] = useState<Location>(defaultLocation)
  const [weather, setWeather] = useState<WeatherData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [favorites, setFavorites] = useState<string[]>(() => JSON.parse(localStorage.getItem('meteora-favorites') || '[]'))
  useEffect(() => { setLoading(true); fetchWeather(location).then(setWeather).catch(() => setError('Live weather is temporarily unavailable. Please retry.')).finally(() => setLoading(false)) }, [location])
  const toggleFavorite = () => setFavorites((old) => { const next = old.includes(location.name) ? old.filter((x) => x !== location.name) : [...old, location.name]; localStorage.setItem('meteora-favorites', JSON.stringify(next)); return next })
  return <AppShell location={location} setLocation={setLocation} favorites={favorites} weather={weather} loading={loading} error={error} toggleFavorite={toggleFavorite} />
}

function AppShell(props: { location: Location; setLocation: (l: Location) => void; favorites: string[]; weather: WeatherData | null; loading: boolean; error: string; toggleFavorite: () => void }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const location = useLocation()
  return <div className="app-shell">
    <header className="nav-wrap"><Link to="/" className="brand"><span className="brand-mark"><CloudSun size={20} /></span><span>Meteora</span></Link>
      <nav className={mobileOpen ? 'nav-links open' : 'nav-links'}>{[['/', 'Overview'], ['/dashboard', 'Dashboard'], ['/forecast', 'Forecast'], ['/map', 'Live map'], ['/cities', 'Cities']].map(([to, label]) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)}>{label}</NavLink>)}</nav>
      <div className="nav-actions"><Link to="/settings" className="settings-link">Preferences</Link><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</button></div>
    </header>
    <AnimatePresence mode="wait"><motion.main key={location.pathname} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .35 }}><Routes>
      <Route path="/" element={<Home {...props} />} /><Route path="/dashboard" element={<Dashboard {...props} />} /><Route path="/forecast" element={<Forecast {...props} />} /><Route path="/map" element={<WeatherMap location={props.location} setLocation={props.setLocation} />} /><Route path="/cities" element={<Cities setLocation={props.setLocation} />} /><Route path="/favorites" element={<Favorites favorites={props.favorites} setLocation={props.setLocation} />} /><Route path="/air-quality" element={<AirQuality />} /><Route path="/weather-stories" element={<Stories />} /><Route path="/settings" element={<Settings />} /><Route path="/about" element={<About />} />
    </Routes></motion.main></AnimatePresence>
    <footer><span>© 2025 Meteora</span><span>Made for the skies everywhere <span className="dot">•</span> Open-Meteo live data</span><Link to="/about">Our story <ArrowUpRight size={14} /></Link></footer>
  </div>
}

function Home(p: Parameters<typeof AppShell>[0]) {
  return <><section className="hero"><div className="hero-video"><video autoPlay muted loop playsInline poster="/images/meteora-weather-poster.jpg" aria-hidden="true"><source src="/videos/meteora-weather-intro.mp4" type="video/mp4" /></video></div><div className="hero-content"><div className="eyebrow"><span className="live-dot" /> Live conditions · around you</div><h1>Weather,<br /><em>reimagined.</em></h1><p>Real-time atmosphere intelligence for every city, coast and hill station around the world.</p><div className="hero-buttons"><Link className="button primary" to="/dashboard">Explore weather <ArrowUpRight size={17} /></Link><button className="button ghost" onClick={() => navigator.geolocation?.getCurrentPosition(({ coords }) => p.setLocation({ name: 'Your location', country: 'India', latitude: coords.latitude, longitude: coords.longitude }))}><Navigation size={16} /> Use my location</button></div></div><div className="hero-weather glass"><div><span className="muted">Now in</span><strong>{p.location.name}<MapPin size={14} /></strong></div>{p.loading ? <div className="skeleton hero-temp" /> : p.weather ? <><div className="hero-temp"><span>{weatherIcon(p.weather.current.code)}</span><b>{Math.round(p.weather.current.temperature)}°</b></div><div className="hero-meta">{weatherLabel(p.weather.current.code)} <span>·</span> Feels like {Math.round(p.weather.current.feelsLike)}°</div></> : <span className="muted">Weather unavailable</span>}<div className="hero-card-footer"><span>Today’s high / low</span><b>{p.weather ? `${Math.round(p.weather.daily.high[0])}° / ${Math.round(p.weather.daily.low[0])}°` : '—'}</b></div></div><div className="scroll-cue"><span /> Scroll to discover</div></section><section className="intro-section"><div className="section-kicker">01 / Your atmosphere</div><div className="intro-copy"><h2>Know the sky<br /><span>before it changes.</span></h2><p>Meteora turns atmospheric data into a clear, calm view of your day. Built for the rhythm of real life — from coastal mornings to cool evenings in the hills.</p><Link to="/dashboard" className="text-link">Enter the dashboard <ArrowUpRight size={15} /></Link></div></section><Dashboard {...p} compact /></>
}

function Dashboard(p: Parameters<typeof AppShell>[0] & { compact?: boolean }) {
  if (p.loading) return <div className="page-container"><Loading /></div>
  if (!p.weather) return <div className="page-container"><ErrorState message={p.error} /></div>
  const w = p.weather
  return <div className={p.compact ? 'dashboard compact' : 'page-container dashboard'}><PageHeading eyebrow="02 / Atmosphere overview" title={p.compact ? 'Your day, at a glance.' : `Good ${new Date().getHours() < 12 ? 'morning' : 'evening'}, ${w.location.name}.`} subtitle="A considered view of the conditions around you." action={<SearchLocation setLocation={p.setLocation} />} /><div className="dashboard-grid"><CurrentCard weather={w} favorite={p.favorites.includes(w.location.name)} toggleFavorite={p.toggleFavorite} /><div className="details-grid"><Detail icon={<Droplets />} label="Humidity" value={`${w.current.humidity}%`} hint="Comfortable" /><Detail icon={<Wind />} label="Wind" value={`${Math.round(w.current.wind)} km/h`} hint={windDirection(w.current.windDirection)} /><Detail icon={<Gauge />} label="Pressure" value={`${Math.round(w.current.pressure)} hPa`} hint="Steady" /><Detail icon={<Eye />} label="Visibility" value={`${w.current.visibility} km`} hint="Clear horizon" /></div></div><section className="forecast-section"><SectionTitle title="Next 24 hours" action={<Link to="/forecast" className="text-link">Full forecast <ArrowUpRight size={14} /></Link>} /><div className="hourly-scroll">{w.hourly.time.map((t, i) => <div className={i === 0 ? 'hour active' : 'hour'} key={t}><span>{i === 0 ? 'Now' : formatHour(t)}</span><i>{weatherIcon(w.hourly.code[i])}</i><b>{Math.round(w.hourly.temperature[i])}°</b><small>{w.hourly.precipitation[i]}% rain</small></div>)}</div></section><div className="split-grid"><section className="chart-card"><SectionTitle title="Temperature trend" action={<span className="chart-legend"><i /> Temperature</span>} /><TemperatureChart weather={w} /></section><section className="week-card"><SectionTitle title="7-day outlook" action={<Link to="/forecast" className="text-link">Details <ArrowUpRight size={14} /></Link>} />{w.daily.time.slice(0, 5).map((day, i) => <div className="day-row" key={day}><span>{i === 0 ? 'Today' : formatDay(day)}</span><i>{weatherIcon(w.daily.code[i])}</i><small>{weatherLabel(w.daily.code[i])}</small><b>{Math.round(w.daily.high[i])}° <span>{Math.round(w.daily.low[i])}°</span></b></div>)}</section></div><section className="ai-card"><div className="ai-icon"><Sparkles size={20} /></div><div><span className="eyebrow">Meteora AI</span><h3>Your weather, explained.</h3><p>Connect a secure server-side AI endpoint to ask about travel, umbrellas, clothing and the best time to step outside.</p></div><span className="setup-badge">Setup required</span></section></div>
}

function CurrentCard({ weather, favorite, toggleFavorite }: { weather: WeatherData; favorite: boolean; toggleFavorite: () => void }) { return <div className="current-card"><div className="card-top"><span className="eyebrow">Current conditions</span><button className={favorite ? 'icon-button selected' : 'icon-button'} onClick={toggleFavorite}><Heart size={17} fill={favorite ? 'currentColor' : 'none'} /></button></div><div className="current-main"><div><h3>{weather.location.name}</h3><p>{weather.location.admin1}, {weather.location.country}</p></div><div className="big-weather-icon">{weatherIcon(weather.current.code)}</div></div><div className="current-reading"><strong>{Math.round(weather.current.temperature)}<sup>°C</sup></strong><div><b>{weatherLabel(weather.current.code)}</b><span>Feels like {Math.round(weather.current.feelsLike)}°</span></div></div><div className="high-low"><span>Today <b>H {Math.round(weather.daily.high[0])}°</b><b>L {Math.round(weather.daily.low[0])}°</b></span><span>Updated {formatHour(weather.current.time)}</span></div></div> }
function Detail({ icon, label, value, hint }: { icon: React.ReactNode; label: string; value: string; hint: string }) { return <div className="detail-card"><div className="detail-icon">{icon}</div><span>{label}</span><b>{value}</b><small>{hint}</small></div> }
function TemperatureChart({ weather }: { weather: WeatherData }) { const data = weather.hourly.time.slice(0, 12).map((t, i) => ({ time: formatHour(t), temp: Math.round(weather.hourly.temperature[i]), rain: weather.hourly.precipitation[i] })); return <div className="chart"><ResponsiveContainer width="100%" height={210}><AreaChart data={data}><defs><linearGradient id="temp" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d8f36a" stopOpacity={.28} /><stop offset="100%" stopColor="#d8f36a" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{ fill: '#6f8498', fontSize: 11 }} /><YAxis hide domain={['dataMin - 2', 'dataMax + 2']} /><Tooltip contentStyle={{ background: '#142332', border: '1px solid #294052', borderRadius: 12 }} /><Area type="monotone" dataKey="temp" stroke="#d8f36a" strokeWidth={3} fill="url(#temp)" dot={false} /></AreaChart></ResponsiveContainer></div> }
function Forecast(p: Parameters<typeof AppShell>[0]) { if (!p.weather) return <div className="page-container"><Loading /></div>; const w = p.weather; return <div className="page-container"><PageHeading eyebrow="03 / Forecast" title="The week ahead." subtitle={`Detailed conditions for ${w.location.name}.`} action={<SearchLocation setLocation={p.setLocation} />} /><div className="forecast-page-grid"><section className="chart-card large"><SectionTitle title="Temperature & rain probability" /><TemperatureChart weather={w} /><div className="forecast-stats"><span><i className="lime-dot" /> Temperature</span><span><i className="blue-dot" /> Precipitation chance</span></div></section><section className="week-card large">{w.daily.time.map((day, i) => <div className="day-row" key={day}><span>{i === 0 ? 'Today' : formatDay(day)}<small>{formatDate(day)}</small></span><i>{weatherIcon(w.daily.code[i])}</i><small>{weatherLabel(w.daily.code[i])}</small><b>{Math.round(w.daily.high[i])}° <span>{Math.round(w.daily.low[i])}°</span></b><em>{w.daily.precipitation[i]}%</em></div>)}</section></div></div> }
function WeatherMap({ location, setLocation }: { location: Location; setLocation: (l: Location) => void }) { return <div className="page-container"><PageHeading eyebrow="04 / Live map" title="The world, in motion." subtitle="Explore live conditions across your saved region." action={<SearchLocation setLocation={setLocation} />} /><div className="map-layout"><div className="map-visual"><div className="map-grid" /><div className="map-state">Meteora</div>{supportedCities.map((city, i) => <button key={city.name} className={city.name === location.name ? 'map-pin selected' : 'map-pin'} style={{ left: `${18 + (city.longitude - 76.6) * 21}%`, top: `${15 + (13.4 - city.latitude) * 30}%` }} onClick={() => setLocation(city)}><span>{city.name === location.name ? '●' : '·'}</span><small>{city.name}</small></button>)}</div><aside className="map-sidebar"><span className="eyebrow">Selected location</span><h3>{location.name}</h3><p>{location.admin1 || location.country}</p><div className="map-stat"><Compass size={18} /><span>Live location<br /><b>Open-Meteo synced</b></span></div><Link className="button primary full" to="/dashboard">View full weather <ArrowUpRight size={16} /></Link></aside></div></div> }
function Cities({ setLocation }: { setLocation: (l: Location) => void }) { const [query, setQuery] = useState(''); const list = supportedCities.filter((x) => x.name.toLowerCase().includes(query.toLowerCase())); return <div className="page-container"><PageHeading eyebrow="05 / Explore" title="Everywhere you want to be." subtitle="Browse the places that make this region remarkable." action={<div className="search-box"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search cities" /></div>} /><div className="city-grid">{list.map((city) => <button className="city-card" key={city.name} onClick={() => setLocation(city)}><span className="city-art">{weatherIcon(2)}</span><div><b>{city.name}</b><small>{city.admin1} · {city.latitude.toFixed(2)}°N</small></div><ArrowUpRight size={18} /></button>)}</div></div> }
function Favorites({ favorites, setLocation }: { favorites: string[]; setLocation: (l: Location) => void }) { const list = supportedCities.filter((x) => favorites.includes(x.name)); return <div className="page-container"><PageHeading eyebrow="06 / Your places" title="Saved skies." subtitle="Your personal collection of places." />{list.length ? <div className="city-grid">{list.map((city) => <button className="city-card" key={city.name} onClick={() => setLocation(city)}><span className="city-art">♡</span><div><b>{city.name}</b><small>Saved location</small></div><ArrowUpRight size={18} /></button>)}</div> : <div className="empty-state"><Heart size={28} /><h3>No saved places yet</h3><p>Tap the heart on any weather card to keep a place close.</p><Link className="button primary" to="/cities">Browse cities</Link></div>}</div> }
function AirQuality() { return <div className="page-container"><PageHeading eyebrow="07 / Air quality" title="Breathe easy." subtitle="A calm read on the air around your location." /><div className="air-card"><div className="aq-score"><span>Air quality index</span><strong>Good</strong><b>32</b><small>Ideal for outdoor activity</small></div><div className="aq-bars">{[['PM2.5','8 μg/m³'],['PM10','18 μg/m³'],['CO','0.2 ppm'],['NO₂','11 ppb'],['O₃','46 ppb']].map(([x,y], i) => <div key={x}><span>{x}</span><div><i style={{ width: `${22 + i * 11}%` }} /></div><b>{y}</b></div>)}</div></div></div> }
function Stories() { return <div className="page-container"><PageHeading eyebrow="08 / Weather stories" title="The weather, told visually." subtitle="A moving portrait of the places we call home." /><div className="stories-grid">{[['Chennai','Coastal clarity','☀'],['Coimbatore','Monsoon rhythm','☂'],['Ooty','Cloud forest','☁'],['Madurai','Golden hour','◑'],['Rameswaram','Sea breeze','◒'],['Hosur','Rain on red earth','☂']].map(([city, desc, icon]) => <div className="story-card" key={city}><div className="story-art"><span>{icon}</span><button><Plus size={17} /></button></div><div><b>{city}</b><small>{desc}</small></div></div>)}</div></div> }
function Settings() { return <div className="page-container narrow"><PageHeading eyebrow="09 / Preferences" title="Make it yours." subtitle="A few considered defaults for your daily forecast." /><div className="settings-card">{[['Temperature','Celsius (°C)'],['Wind speed','Kilometres per hour'],['Language','English'],['Alerts','Rain and severe weather']].map(([x,y]) => <div className="setting-row" key={x}><span><b>{x}</b><small>{y}</small></span><button className="toggle on"><i /></button></div>)}</div></div> }
function About() { return <div className="page-container narrow"><div className="about-card"><span className="eyebrow">The idea behind Meteora</span><h1>Weather should feel<br /><em>human.</em></h1><p>Meteora is a portfolio exploration in making live weather data feel less like a spreadsheet and more like a daily ritual. Built with the Open-Meteo API for the places and people who keep looking up.</p><div className="about-sign">Meteora <span>— 2025</span></div></div></div> }
function SearchLocation({ setLocation }: { setLocation: (l: Location) => void }) { const [value, setValue] = useState(''); const [results, setResults] = useState<Location[]>([]); useEffect(() => { if (value.length < 2) { setResults([]); return } const timer = setTimeout(() => searchLocations(value).then(setResults).catch(() => setResults([])), 350); return () => clearTimeout(timer) }, [value]); return <div className="search-wrap"><div className="search-box"><Search size={17} /><input value={value} onChange={(e) => setValue(e.target.value)} placeholder="Search a city..." /></div>{results.length > 0 && <div className="search-results">{results.map((x) => <button key={`${x.name}-${x.latitude}`} onClick={() => { setLocation(x); setValue(''); setResults([]) }}><MapPin size={14} /><span>{x.name}<small>{x.admin1}, {x.country}</small></span></button>)}</div>}</div> }
function PageHeading({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div> }
function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="section-title"><h2>{title}</h2>{action}</div> }
function Loading() { return <div className="loading-state"><div className="spinner" /><p>Reading the atmosphere...</p></div> }
function ErrorState({ message }: { message: string }) { return <div className="empty-state"><Umbrella size={28} /><h3>Weather drifted away</h3><p>{message}</p><button className="button primary" onClick={() => location.reload()}><RefreshCw size={16} /> Retry</button></div> }
function windDirection(degrees: number) { return ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][Math.round(degrees / 45) % 8] }

export default App
